# .streamlit/secrets.toml

[gcp_service_account]
type = "service_account"
project_id = "misiddons-book-databse"
private_key_id = "60d1f59560c72ef9db9a76ce0ccfe0433b9e5231"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDk2rBkbVbG5PyS
... (the rest of your private key) ...
2ITvqUz+d4WP+W+SLG/AFQ==
-----END PRIVATE KEY-----"""
client_email = "streamlit-sheets@misiddons-book-databse.iam.gserviceaccount.com"
client_id = "118161071424045291399"
token_uri = "https://oauth2.googleapis.com/token"
