# .streamlit/secrets.toml

[connections.gsheets]
spreadsheet = "YOUR_GOOGLE_SHEET_URL"

# The following is copied from your JSON file
type = "service_account"
project_id = "misiddons-book-databse"
private_key_id = "60d1f59560c72ef9db9a76ce0ccfe0433b9e5231"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDk2rBkbVbG5PyS
A6lbm/OV9R787pdWpuv33POmW2Nbx00fOrwooZBKFdDv6n3VotK9QFsRACPZYy4b
8LCxdNpa/f4nzzCp+77h9svzBnLZa1AjwzY3T3dLfIYDUpZdDnMx6Oo2zYefhnyr
JfGPN2gWrzVj3IRmyIVqGAmXUpOyZYfm53l/1iODl/JCpzOc+T+Q4gicVd62m/TR
rT8uDMVRytFUdGI0ALKO4GsBtpLR7ompEf8q266l8WcosaKRmrI9xOyU3wE56uKU
J3Uc0cU+DdIEwtL7Yr2xNg+H0uoe/Xi+dhNsW16A1cgKbjmIy6Fk7RdOtI4NIp64
OHhnAZOpAgMBAAECggEAY83voUyBzKmucGtCX55Kg7prsjjHLVYMkIL+iy1NzofD
XXw69KlJCNYs0YR9Lj8dEsXPMUHTYIm9YRf9ptZkJ8yfG3NjMK6GV3tPBIRqb+E6
CO6oZUS1rOj4dNh+lMSpfjmqcw39OJfpJKaeiyvJrCLq8MsJvt1yOYuUGzc7DFAh
2AWS/ToTvu+eU7cwwTB1ceF3E9pcdEwlRLW29cNrSzKAToVD8H5mW3msy73cjR6r
cWJf+ah8ztI6/zoGiYZt/XqLEk8qkdYkbRc2CavLl581bPzkGQSmedKXj3soDG7k
Ey/XWjqxqJhHD7L+3WUQxQFpSf6XYxnq5fTq1rjMpQKBgQD5O+Fshn+1IXCh/V5H
2+BwmJLw/tzn314KDzG3TaVih7v27ricMg6URVaErZ4mQZWgcCngOfxHWMlgmTDz
GsyB3C6qY1HjUcFTr5+0IhLVCx+ZFKZCXUgBzTWC9+uj68Ka9lM+Nq1Z4zFZFzm3
IIx6yj2r0IOb2toedXe23THHzwKBgQDrESyqCWfoErXu+gqaVO4mSeh0UTVs+ktP
xy0Y526D4T/hFEFoZCWz+AMDiuEl1u0uHnnrcBf/pfJdqczbm7MZMT3CLCgwwJxd
3CijZ46WBmzNY7UxAJ/t1u7rE2LAK9dJbSI6V7Bmzwy5CuMMpWNF3RBeKUnzWsi2
Ja4glZNTBwKBgA1Kkzf9aDwZn28UGv4MDMkUaemuPcujztkMfGNBIcvCX1TI4FF8
HejsVbPXqnJx1u/qa2FI1lpbssmTAdhFGpjmTBrMFybfSkcTO5oYoxZ3dGTug/tQ
DDIEZpEodYmVXhhzgHb15YLAqfYNVgedFcDKnkVWZl5eanlrXEoFO81jAoGABzwL
FNyfPww8XzOA2gkdHz6NEe9h5o25faYSpD6TLynijmnSLYVPh79tUFGY5lI8EHxN
okpb4rlXwTw1mtiq5W6XiP9U6VM0PMtG0OiiAcoG1TdpXy22vlosFj4Nfv6abJ8Y
O5VxT2i16ogEPuJkMMVB+LPqm7vCi6CTQFt6IkcCgYBRSmlMzTWEPxxAWTmQSTZl
+S9Lm9JNBLZwUcRq2tYtXX30fb+91naDXQmZQvNevnH0AjVbJoiH7nF6RVSVihSE
E4m9cYNo6SB3JzscxDTAN+7XGPxjcmX9jxwpB0TYvabzMOF5juhvoTBajtAHIqgk
2ITvqUz+d4WP+W+SLG/AFQ==
-----END PRIVATE KEY-----"""
client_email = "streamlit-sheets@misiddons-book-databse.iam.gserviceaccount.com"
client_id = "118161071424045291399"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-sheets%40misiddons-book-databse.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
