[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/......../edit"

type           = "service_account"
project_id     = "misdiddons-book-databse"
private_key_id = "xxxxxxxxxxxxxxxxxxxx"
private_key    = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBK...
... (EVERY line from the JSON, untouched) ...
-----END PRIVATE KEY-----"""
client_email   = "streamlit-sheets@misdiddons-book-databse.iam.gserviceaccount.com"
client_id      = "xxxxxxxxxxxxxxxxxxxx"
token_uri      = "https://oauth2.googleapis.com/token"
