# Use this new content for your secrets.toml file

[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1AXupO4-kABwoz88H2dYfc6hv6wzooh7f8cDnIRl0Q7s/edit?gid=0#gid=0"

# Values from your new JSON file
type = "service_account"
project_id = "misiddons-book-databse"
private_key_id = "2053f224ebd3c032df3b36717d726415838320b5"
client_email = "book-app-connector@misiddons-book-databse.iam.gserviceaccount.com"
client_id = "109456693627613128502"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEuwIBADANBgkqhkiG9w0BAQEFAASCBKUwggShAgEAAoIBAQDkJZm/aAcgq5Bk
OH7Pc10Xie5phdKcNWppD3D+JSxbzq8TiW91FKIr7H27ZuYJkAnfVyDuMDHrAWup
toWaAmTVWSuKD3y/u5ndrB8TPV6+Ik6r75XDvLws1QKAkvwh3mPBH3Ls/rP6b0VC
VY9n4Yqb0r1ZcMLBjmnVDqZH8VibHSJ01aa8eLCFM+KZKJlUHUpuHU/rwRUYjLWz
jxtSIBI0ntoOFWSjdiLQWmyj8crGpBQgxFX74/aB5Ndn5RT43R1YCd8QRKbxBcQz
uTXuFxW/hliHsvaiqEJAB3EiVsvG9hNbfnwLy11k67ilkgdtneLB0KhgLKKjev/N
JNKe7ggZAgMBAAECgf9DdLM75MFKcW+iWa9zpvdB1xBYIupxbLwxGP08ADfiT7A5
KkJAW9lv6C3iTrG1XTAEO5dZmped+DAEdBpu+LxhbCNzc5b4yvVRC7qakzvmNtwf
q1ScspOOXx4Pg41/E6SSYaZeRPDKpQf8vGM0LGfi5c7vGSzyg+4B1bV73sx7Xqae
l7dGGUaFapqyMOipakHJcu8X+hU5IxKftDLf32r7Blrl8tfVnOqU81sCNgJsY+Bb
bY0ek1evO0hNgaZaKpfBxYbKVzaosyQLOg3I014a9JUqmPLrrbyzDPRWwuhZje4d
tmtVzHjugFVd8BdsyI0ANpOcMod7fhTYGIa9UeECgYEA+IQIgwb5joAmBg3hw2FG
C/SUhtc5oxPwJ7N+yqITuU/H+qMLxE/f48ocbBx22OsiTE2Ll+jCr+cL1jVfDvif
KEPlPyWyd00LXC3wD9p8HlJfjkol9pidA7zKczFp0zw+i2sFMfs2VWUPZtOaZ4hH
9wrAR5/JCbyeXa08KlCYImMCgYEA6wSH16w8wTlZJQJXyCMtHMBAn7NFBu9QoIAJ
5BCWSP/1vNEI8KuKV1dXtb1/051HArIxP1hsuLea8ApkXNpcD9/rNfNYarLXLlpl
b6ogb5hJaAHidr4JBQnwoljpRnmLZav1Zb2iK4NU6z3MMBmH9D/tYmPBTgRyZrWu
8wJeNlMCgYAxLaeljjbKXU+o+QxJJrG+4eqWeHbeb66hnKKlpMc0b7ZKQgOtGIVc
xX00Y7mdGYLTCLFsIVKNjrJH9I3YH5kXVcBC68nSU/vAhRKxgHH5aiGgvcmfb/n6
aFzDyO6BL7XMzyPbDTRmV7ZhidRPUqezGnyMb/FPrPTF4uc6FHLWswKBgQDdOc+R
kl1CWfRzJQhyqcIebU6nxf21MHMKEly9JWwCXYb5bR/oROGdo+c5eZ8pGMSuYgR/
p4H4Q0UCrhWZXicI/nQPvfi9v4lU5dzURyXvRj/bOuLteadN6fRtLhqwr1sroroG
QoK0SRUXt31MzcuvfLm9Qz/Ea+Uwj9eWguUiZwKBgBxkRVPoll6Hdcy/cstqkmTI
W5yKbOBBD3PBFYy9SGSOe8U35qUYuDUz4LsO6mNNgrkVe55kmC7QKfIZmj9d7Uc4
lbherC/6xtktQOMKhwBbDIZsg2fFa8ppWLsyU16gTABdFX8Fb4IxGilhGjAdhSNc
Bb1MhFBm5KF2TRbN70jy
-----END PRIVATE KEY-----"""
