[connections.gsheets]
# Replace with the full URL of your Google Sheet
spreadsheet = "https://docs.google.com/spreadsheets/d/<YOUR-SHEET-ID>"

# The following values are copied from your JSON credentials file
type = "service_account"
project_id = "misiddons-book-databse"
private_key_id = "60d1f59560c72ef9db9a76ce0ccfe0433b9e5231"
client_email = "streamlit-sheets@misiddons-book-databse.iam.gserviceaccount.com"
client_id = "118161071424045291399"
token_uri = "https://oauth2.googleapis.com/token"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDk2rBkbVbG5PyS
A6lbm/OV9R787pdWpuv33POmW2Nbx00fOrwooZBKFdDv6n3VotK9QFsRACPZYy4b
... (rest of your private key) ...
Ja4glZNTBwKBgA1Kkzf9aDwZn28UGv4MDMkUaemuPcujztkMfGNBIcvCX1TI4FF8
HejsVbPXqnJx1u/qa2FI1lpbssmTAdhFGpjmTBrMFybfSkcTO5oYoxZ3dGTug/tQ
DDIEZpEodYmVXhhzgHb15YLAqfYNVgedFcDKnkVWZl5eanlrXEoFO81jAoGABzwL
FNyfPww8XzOA2gkdHz6NEe9h5o25faYSpD6TLynijmnSLYVPh79tUFGY5lI8EHxN
okpb4rlXwTw1mtiq5W6XiP9U6VM0PMtG0OiiAcoG1TdpXy22vlosFj4Nfv6abJ8Y
O5VxT2i16ogEPuJkMMVB+LPqm7vCi6CTQFt6IkcCgYBRSmlMzTWEPxxAWTmQSTZl
+S9Lm9JNBLZwUcRq2tYtXX30fb+91naDXQmZQvNevnH0AjVbJoiH7nF6RVSVihSE
E4m9cYNo6SB3JzscxDTAN+7XGPxjcmX9jxwpB0TYvabzMOF5juhvoTBajtAHIqgk
2ITvqUz+d4WP+W+SLG/AFQ==
-----END PRIVATE KEY-----"""
