[connections.gsheets]
# Spreadsheet URL up to (and including) the sheet-ID
spreadsheet = "https://docs.google.com/spreadsheets/d/<YOUR-SHEET-ID>"

type           = "service_account"
project_id     = "misiddons-book-databse"
private_key_id = "60d1f59560c72ef9db9a76ce0ccfe0433b9e5231"

# ⇩⇩  Paste the key exactly once between these triple quotes  ⇩⇩
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDk2rBkbVbG5PyS
A6lbm/OV9R787pdWpuv33POmW2Nbx00fOrwooZBKFdDv6n3VotK9QFsRACPZYy4b
… (every line from your JSON key — *no* “\n”, no edits) …
-----END PRIVATE KEY-----"""

client_email = "streamlit-sheets@misiddons-book-databse.iam.gserviceaccount.com"
client_id    = "118161071424045291399"
token_uri    = "https://oauth2.googleapis.com/token"
