[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/XXXXXXXXXXXXXXXXXXXXXXXXXXXX/edit"

type           = "service_account"
project_id     = "misdiddons-book-databse"               # ← from JSON
private_key_id = "YOUR_PRIVATE_KEY_ID"                   # ← from JSON
private_key    = """-----BEGIN PRIVATE KEY-----
YOUR
MULTI-LINE
KEY
-----END PRIVATE KEY-----"""
client_email   = "streamlit-sheets@misdiddons-book-databse.iam.gserviceaccount.com"
client_id      = "YOUR_CLIENT_ID"
token_uri      = "https://oauth2.googleapis.com/token"
